### ISSUE TITLE
Update dependent repositories

### ISSUE THREAD

**Issue by SoupyzInc** [rancslab/carma-platform-archive#1]
In [carma-platform.repos](https://github.com/rancslab/carma-platform/blob/develop/carma-platform.repos).
- [x] Use our `carma-config`
- [x] Use VT's `autoware.ai` (for twist)
- [x] Include VT's Outser LiDAR driver
- [x] Include VT's Dataspeed CAN driver
- [x] Include VT's Dataspeed ULC driver

**Comment by DongTrung28** [comment]
Fix with commit aad4f1fa0c760dfdfe4762314a7ce9e3d7e2dfea
